### ISSUE TITLE
请教个问题：收到压缩包，但其中只有一个py代码，并没有支付宝申请教程啥的，是我遗漏了什么不？

### ISSUE THREAD

**Issue by Yvees** [huvipg/bpay#2]
RT

**Comment by huvipg** [comment]
https://github.com/huvipg/bpay/blob/master/%E7%94%B3%E8%AF%B7%E6%94%AF%E4%BB%98%E5%AE%9D%E5%BD%93%E9%9D%A2%E4%BB%98%E6%95%99%E7%A8%8B.md
